//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGalleryBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageGalleryBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap an_thumbnail {
            get {
                object obj = ResourceManager.GetObject("an_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg_back {
            get {
                object obj = ResourceManager.GetObject("bg_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ct_back {
            get {
                object obj = ResourceManager.GetObject("ct_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deletered {
            get {
                object obj = ResourceManager.GetObject("deletered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg__start32grey {
            get {
                object obj = ResourceManager.GetObject("dg_ start32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_corvers {
            get {
                object obj = ResourceManager.GetObject("dg_back_corvers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_ct {
            get {
                object obj = ResourceManager.GetObject("dg_back_ct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_info {
            get {
                object obj = ResourceManager.GetObject("dg_back_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_lb {
            get {
                object obj = ResourceManager.GetObject("dg_back_lb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_lc {
            get {
                object obj = ResourceManager.GetObject("dg_back_lc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_lr {
            get {
                object obj = ResourceManager.GetObject("dg_back_lr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_lt {
            get {
                object obj = ResourceManager.GetObject("dg_back_lt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_rb {
            get {
                object obj = ResourceManager.GetObject("dg_back_rb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_rc {
            get {
                object obj = ResourceManager.GetObject("dg_back_rc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_rt {
            get {
                object obj = ResourceManager.GetObject("dg_back_rt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_back_tb {
            get {
                object obj = ResourceManager.GetObject("dg_back_tb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_cancel48color {
            get {
                object obj = ResourceManager.GetObject("dg_cancel48color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_cancel48grey {
            get {
                object obj = ResourceManager.GetObject("dg_cancel48grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_close {
            get {
                object obj = ResourceManager.GetObject("dg_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#333333;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:white;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover {
        ///	border-bottom:none;
        ///	color:white;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 auto;
        ///	position:relative;
        ///}
        ///
        ///#onsbo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dg_css {
            get {
                return ResourceManager.GetString("dg_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap dg_dg_back_cb {
            get {
                object obj = ResourceManager.GetObject("dg_dg_back_cb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_loading {
            get {
                object obj = ResourceManager.GetObject("dg_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_navigation {
            get {
                object obj = ResourceManager.GetObject("dg_navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_next {
            get {
                object obj = ResourceManager.GetObject("dg_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_next1 {
            get {
                object obj = ResourceManager.GetObject("dg_next1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_next32_color {
            get {
                object obj = ResourceManager.GetObject("dg_next32-color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_next32_grey {
            get {
                object obj = ResourceManager.GetObject("dg_next32-grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_pause32color {
            get {
                object obj = ResourceManager.GetObject("dg_pause32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_pause32grey {
            get {
                object obj = ResourceManager.GetObject("dg_pause32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_prev {
            get {
                object obj = ResourceManager.GetObject("dg_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_prev_32color {
            get {
                object obj = ResourceManager.GetObject("dg_prev-32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_prev_32grey {
            get {
                object obj = ResourceManager.GetObject("dg_prev-32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_prev1 {
            get {
                object obj = ResourceManager.GetObject("dg_prev1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_start32color {
            get {
                object obj = ResourceManager.GetObject("dg_start32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dg_thumbnail {
            get {
                object obj = ResourceManager.GetObject("dg_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_save {
            get {
                object obj = ResourceManager.GetObject("document_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap down_256 {
            get {
                object obj = ResourceManager.GetObject("down_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap downx {
            get {
                object obj = ResourceManager.GetObject("downx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_back {
            get {
                object obj = ResourceManager.GetObject("fb_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderBottomCenter {
            get {
                object obj = ResourceManager.GetObject("fb_borderBottomCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderBottomLeft {
            get {
                object obj = ResourceManager.GetObject("fb_borderBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderBottomRight {
            get {
                object obj = ResourceManager.GetObject("fb_borderBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderMiddleLeft {
            get {
                object obj = ResourceManager.GetObject("fb_borderMiddleLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderMiddleRight {
            get {
                object obj = ResourceManager.GetObject("fb_borderMiddleRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderTopCenter {
            get {
                object obj = ResourceManager.GetObject("fb_borderTopCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderTopLeft {
            get {
                object obj = ResourceManager.GetObject("fb_borderTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_borderTopRight {
            get {
                object obj = ResourceManager.GetObject("fb_borderTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_close {
            get {
                object obj = ResourceManager.GetObject("fb_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_closelabel {
            get {
                object obj = ResourceManager.GetObject("fb_closelabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#151410;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:#151410;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover {
        ///	border-bottom:none;
        ///	color:#151410;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 auto;
        ///	position:relative;
        ///}
        ///
        ///#o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fb_css {
            get {
                return ResourceManager.GetString("fb_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fb_loading {
            get {
                object obj = ResourceManager.GetObject("fb_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_next {
            get {
                object obj = ResourceManager.GetObject("fb_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_next_ie6 {
            get {
                object obj = ResourceManager.GetObject("fb_next_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_nextlabel {
            get {
                object obj = ResourceManager.GetObject("fb_nextlabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_pause {
            get {
                object obj = ResourceManager.GetObject("fb_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_prev {
            get {
                object obj = ResourceManager.GetObject("fb_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_prev_ie6 {
            get {
                object obj = ResourceManager.GetObject("fb_prev_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_prevlabel {
            get {
                object obj = ResourceManager.GetObject("fb_prevlabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_start {
            get {
                object obj = ResourceManager.GetObject("fb_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fb_thumbnail {
            get {
                object obj = ResourceManager.GetObject("fb_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder__1_ {
            get {
                object obj = ResourceManager.GetObject("folder (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back {
            get {
                object obj = ResourceManager.GetObject("in_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_cb {
            get {
                object obj = ResourceManager.GetObject("in_back_cb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_corvers {
            get {
                object obj = ResourceManager.GetObject("in_back_corvers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_ct {
            get {
                object obj = ResourceManager.GetObject("in_back_ct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_info {
            get {
                object obj = ResourceManager.GetObject("in_back_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_lb {
            get {
                object obj = ResourceManager.GetObject("in_back_lb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_lc {
            get {
                object obj = ResourceManager.GetObject("in_back_lc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_lr {
            get {
                object obj = ResourceManager.GetObject("in_back_lr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_lt {
            get {
                object obj = ResourceManager.GetObject("in_back_lt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_rb {
            get {
                object obj = ResourceManager.GetObject("in_back_rb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_rc {
            get {
                object obj = ResourceManager.GetObject("in_back_rc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_rt {
            get {
                object obj = ResourceManager.GetObject("in_back_rt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_back_tb {
            get {
                object obj = ResourceManager.GetObject("in_back_tb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_cancel48color {
            get {
                object obj = ResourceManager.GetObject("in_cancel48color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_cancel48grey {
            get {
                object obj = ResourceManager.GetObject("in_cancel48grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_close {
            get {
                object obj = ResourceManager.GetObject("in_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#000000;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:white;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover {
        ///	border-bottom:none;
        ///	color:white;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 aut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string in_css {
            get {
                return ResourceManager.GetString("in_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap in_loading {
            get {
                object obj = ResourceManager.GetObject("in_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_navigation {
            get {
                object obj = ResourceManager.GetObject("in_navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_next {
            get {
                object obj = ResourceManager.GetObject("in_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_next32_color {
            get {
                object obj = ResourceManager.GetObject("in_next32-color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_next32_grey {
            get {
                object obj = ResourceManager.GetObject("in_next32-grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_pause32color {
            get {
                object obj = ResourceManager.GetObject("in_pause32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_pause32grey {
            get {
                object obj = ResourceManager.GetObject("in_pause32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_prev {
            get {
                object obj = ResourceManager.GetObject("in_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_prev_32color {
            get {
                object obj = ResourceManager.GetObject("in_prev-32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_prev_32grey {
            get {
                object obj = ResourceManager.GetObject("in_prev-32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_start32color {
            get {
                object obj = ResourceManager.GetObject("in_start32color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap in_start32grey {
            get {
                object obj = ResourceManager.GetObject("in_start32grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back {
            get {
                object obj = ResourceManager.GetObject("ip_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_cb {
            get {
                object obj = ResourceManager.GetObject("ip_back_cb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_corvers {
            get {
                object obj = ResourceManager.GetObject("ip_back_corvers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_ct {
            get {
                object obj = ResourceManager.GetObject("ip_back_ct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_lb {
            get {
                object obj = ResourceManager.GetObject("ip_back_lb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_lc {
            get {
                object obj = ResourceManager.GetObject("ip_back_lc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_lr {
            get {
                object obj = ResourceManager.GetObject("ip_back_lr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_lt {
            get {
                object obj = ResourceManager.GetObject("ip_back_lt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_rb {
            get {
                object obj = ResourceManager.GetObject("ip_back_rb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_rc {
            get {
                object obj = ResourceManager.GetObject("ip_back_rc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_rt {
            get {
                object obj = ResourceManager.GetObject("ip_back_rt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_back_tb {
            get {
                object obj = ResourceManager.GetObject("ip_back_tb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_bk {
            get {
                object obj = ResourceManager.GetObject("ip_bk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#000000;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:#707070;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover{
        ///	border-bottom:none;
        ///	color:#707070;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 auto;
        ///	position:relative;
        ///}
        ///
        ///#on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ip_css {
            get {
                return ResourceManager.GetString("ip_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ip_loading {
            get {
                object obj = ResourceManager.GetObject("ip_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_navigation {
            get {
                object obj = ResourceManager.GetObject("ip_navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_navigation1 {
            get {
                object obj = ResourceManager.GetObject("ip_navigation1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_next {
            get {
                object obj = ResourceManager.GetObject("ip_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_next1 {
            get {
                object obj = ResourceManager.GetObject("ip_next1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_prev {
            get {
                object obj = ResourceManager.GetObject("ip_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_prev1 {
            get {
                object obj = ResourceManager.GetObject("ip_prev1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ip_thumbnail {
            get {
                object obj = ResourceManager.GetObject("ip_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 
        /// * jQuery JavaScript Library v1.4.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://docs.jquery.com/License
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// * 
        /// * -----
        /// * 
        /// 
        ///
        /// * File generated: Wed Sep 22 06:12:53 GMT 2010
        /// */
        ///(function(A,w){function ma(){if(!c.isReady){try{s.documentElement.doScroll(&quot;left&quot;)}catch(a){setTimeout(ma,1);return [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_min {
            get {
                return ResourceManager.GetString("js_min", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mc_back {
            get {
                object obj = ResourceManager.GetObject("mc_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderBottomCenter {
            get {
                object obj = ResourceManager.GetObject("mc_borderBottomCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderBottomLeft {
            get {
                object obj = ResourceManager.GetObject("mc_borderBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderBottomRight {
            get {
                object obj = ResourceManager.GetObject("mc_borderBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderMiddleLeft {
            get {
                object obj = ResourceManager.GetObject("mc_borderMiddleLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderMiddleRight {
            get {
                object obj = ResourceManager.GetObject("mc_borderMiddleRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderTopCenter {
            get {
                object obj = ResourceManager.GetObject("mc_borderTopCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderTopLeft {
            get {
                object obj = ResourceManager.GetObject("mc_borderTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_borderTopRight {
            get {
                object obj = ResourceManager.GetObject("mc_borderTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_close {
            get {
                object obj = ResourceManager.GetObject("mc_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_closelabel {
            get {
                object obj = ResourceManager.GetObject("mc_closelabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#ffffff;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:#151410;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover {
        ///	border-bottom:none;
        ///	color:#151410;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 auto;
        ///	position:relative;
        ///}
        ///
        ///#o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mc_css {
            get {
                return ResourceManager.GetString("mc_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mc_loading {
            get {
                object obj = ResourceManager.GetObject("mc_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_next {
            get {
                object obj = ResourceManager.GetObject("mc_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_next_ie6 {
            get {
                object obj = ResourceManager.GetObject("mc_next_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_nextlabel {
            get {
                object obj = ResourceManager.GetObject("mc_nextlabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_pause {
            get {
                object obj = ResourceManager.GetObject("mc_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_prev {
            get {
                object obj = ResourceManager.GetObject("mc_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_prev_ie6 {
            get {
                object obj = ResourceManager.GetObject("mc_prev_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_prevlabel {
            get {
                object obj = ResourceManager.GetObject("mc_prevlabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_start {
            get {
                object obj = ResourceManager.GetObject("mc_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mc_thumbnail {
            get {
                object obj = ResourceManager.GetObject("mc_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function($){$.fn.ons_galary=function(options){var C=null,badObjects=[&quot;select&quot;,&quot;object&quot;,&quot;embed&quot;],l=null,B=[],k=null,c=null,m=50,I,showTimer;if(!document.getElementsByTagName){return;}options=$.extend({animate:true,autoPlay:true,borderSize:39,containerID:document,enableSlideshow:true,googleAnalytics:false,descSliding:true,imageDataLocation:&quot;south&quot;,shadowLocation:&quot;&quot;,closeLocation:&quot;&quot;,initImage:&quot;&quot;,loop:true,overlayDuration:0.2,overlayOpacity:0.7,prefix:&quot;&quot;,classNames:&quot;vonsbox&quot;,resizeSpeed:7,Ae:false,slideTime:4, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ons_galary {
            get {
                return ResourceManager.GetString("ons_galary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery(document).ready(function(){ window.onsbox = new jQuery().ons_galary({autoPlay:true,borderSize:21,classNames:&apos;vonsbox,onsbox1&apos;,descSliding:true,enableRightClick:false,enableSlideshow:true,overlayOpacity:0.7,resizeSpeed:7,slideTime:4,startZoom:true}) });
        ///.
        /// </summary>
        internal static string onsdata {
            get {
                return ResourceManager.GetString("onsdata", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap preferences_desktop_personal {
            get {
                object obj = ResourceManager.GetObject("preferences_desktop_personal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap publish {
            get {
                object obj = ResourceManager.GetObject("publish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_config_boot {
            get {
                object obj = ResourceManager.GetObject("system_config_boot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap up_256 {
            get {
                object obj = ResourceManager.GetObject("up_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upx {
            get {
                object obj = ResourceManager.GetObject("upx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_back {
            get {
                object obj = ResourceManager.GetObject("vt_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_back1 {
            get {
                object obj = ResourceManager.GetObject("vt_back1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderBottomCenter {
            get {
                object obj = ResourceManager.GetObject("vt_borderBottomCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderBottomLeft {
            get {
                object obj = ResourceManager.GetObject("vt_borderBottomLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderBottomRight {
            get {
                object obj = ResourceManager.GetObject("vt_borderBottomRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderMiddleLeft {
            get {
                object obj = ResourceManager.GetObject("vt_borderMiddleLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderMiddleRight {
            get {
                object obj = ResourceManager.GetObject("vt_borderMiddleRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderTopCenter {
            get {
                object obj = ResourceManager.GetObject("vt_borderTopCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderTopLeft {
            get {
                object obj = ResourceManager.GetObject("vt_borderTopLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_borderTopRight {
            get {
                object obj = ResourceManager.GetObject("vt_borderTopRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_close {
            get {
                object obj = ResourceManager.GetObject("vt_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_conposit {
            get {
                object obj = ResourceManager.GetObject("vt_conposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #overlay{
        ///	position:absolute;
        ///	top:0;
        ///	left:0;
        ///	z-index:90;
        ///	width:100%;
        ///	height:auto;
        ///	background-color:#ffffff;
        ///}
        ///
        ///#onsbox{
        ///	position:absolute;
        ///	top:20px;
        ///	left:0;
        ///	width:100%;
        ///	z-index:100;
        ///	text-align:center;
        ///	color:#151410;
        ///	line-height:0;
        ///}
        ///
        ///#onsbox a, #onsbox a:hover {
        ///	border-bottom:none;
        ///	color:#151410;
        ///	text-decoration:underline;
        ///}
        ///
        ///#onsbox a img{ border:none; }
        ///
        ///#outerImageContainer{
        ///	width:auto;
        ///	height:auto; /* without this line error in IE8 detected */
        ///	margin:0 auto;
        ///	position:relative;
        ///}
        ///
        ///#o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vt_css {
            get {
                return ResourceManager.GetString("vt_css", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap vt_loading {
            get {
                object obj = ResourceManager.GetObject("vt_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_next {
            get {
                object obj = ResourceManager.GetObject("vt_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_next_ie6 {
            get {
                object obj = ResourceManager.GetObject("vt_next_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_prev {
            get {
                object obj = ResourceManager.GetObject("vt_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_prev_ie6 {
            get {
                object obj = ResourceManager.GetObject("vt_prev_ie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vt_thumbnail {
            get {
                object obj = ResourceManager.GetObject("vt_thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
